server:
  port: 8009

eureka:
  client:
    service-url:
      # defaultZone: http://172.31.183.101:8008/eureka/
      defaultZone: http://127.0.0.1:8008/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

spring:
  redis:
    database: 2
    host: redis
    port: 6379
    password: shmashine@666
    timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1n9d80pc03n1ag4qo.mysql.rds.aliyuncs.com:3306/elevator_master?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: wuyanjie
    password: Maixin480

  boot:
    admin:
      client:
        url: http://spring-boot-admin:8080/
        username: shmashine
        password: shmashine
        instance:
          prefer-ip: true
          # service-url: http://172.31.183.101:8009
          service-url: http://127.0.0.1:8009