package com.shmashine.model;

import java.io.Serializable;
import java.util.Date;

public class TblSysUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_user_id
     *
     * @mbg.generated
     */
    private String v_user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_username
     *
     * @mbg.generated
     */
    private String v_username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_password
     *
     * @mbg.generated
     */
    private String v_password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.open_id
     *
     * @mbg.generated
     */
    private String open_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_name
     *
     * @mbg.generated
     */
    private String v_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_email
     *
     * @mbg.generated
     */
    private String v_email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_mobile
     *
     * @mbg.generated
     */
    private String v_mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.i_status
     *
     * @mbg.generated
     */
    private Integer i_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_sex
     *
     * @mbg.generated
     */
    private Long v_sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_birth
     *
     * @mbg.generated
     */
    private Date v_birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_pic_id
     *
     * @mbg.generated
     */
    private String v_pic_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_provincial_city
     *
     * @mbg.generated
     */
    private String v_provincial_city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_address
     *
     * @mbg.generated
     */
    private String v_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_hobby
     *
     * @mbg.generated
     */
    private String v_hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.i_work_order_flag
     *
     * @mbg.generated
     */
    private Integer i_work_order_flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.i_send_phone_status
     *
     * @mbg.generated
     */
    private Integer i_send_phone_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.i_send_message_status
     *
     * @mbg.generated
     */
    private Integer i_send_message_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.dt_createTime
     *
     * @mbg.generated
     */
    private Date dt_createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.dt_modifyTime
     *
     * @mbg.generated
     */
    private Date dt_modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_createid
     *
     * @mbg.generated
     */
    private String v_createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_user.v_modifyid
     *
     * @mbg.generated
     */
    private String v_modifyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_user_id
     *
     * @return the value of tbl_sys_user.v_user_id
     * @mbg.generated
     */
    public String getV_user_id() {
        return v_user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_user_id
     *
     * @param v_user_id the value for tbl_sys_user.v_user_id
     * @mbg.generated
     */
    public void setV_user_id(String v_user_id) {
        this.v_user_id = v_user_id == null ? null : v_user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_username
     *
     * @return the value of tbl_sys_user.v_username
     * @mbg.generated
     */
    public String getV_username() {
        return v_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_username
     *
     * @param v_username the value for tbl_sys_user.v_username
     * @mbg.generated
     */
    public void setV_username(String v_username) {
        this.v_username = v_username == null ? null : v_username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_password
     *
     * @return the value of tbl_sys_user.v_password
     * @mbg.generated
     */
    public String getV_password() {
        return v_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_password
     *
     * @param v_password the value for tbl_sys_user.v_password
     * @mbg.generated
     */
    public void setV_password(String v_password) {
        this.v_password = v_password == null ? null : v_password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.open_id
     *
     * @return the value of tbl_sys_user.open_id
     * @mbg.generated
     */
    public String getOpen_id() {
        return open_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.open_id
     *
     * @param open_id the value for tbl_sys_user.open_id
     * @mbg.generated
     */
    public void setOpen_id(String open_id) {
        this.open_id = open_id == null ? null : open_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_name
     *
     * @return the value of tbl_sys_user.v_name
     * @mbg.generated
     */
    public String getV_name() {
        return v_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_name
     *
     * @param v_name the value for tbl_sys_user.v_name
     * @mbg.generated
     */
    public void setV_name(String v_name) {
        this.v_name = v_name == null ? null : v_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_email
     *
     * @return the value of tbl_sys_user.v_email
     * @mbg.generated
     */
    public String getV_email() {
        return v_email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_email
     *
     * @param v_email the value for tbl_sys_user.v_email
     * @mbg.generated
     */
    public void setV_email(String v_email) {
        this.v_email = v_email == null ? null : v_email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_mobile
     *
     * @return the value of tbl_sys_user.v_mobile
     * @mbg.generated
     */
    public String getV_mobile() {
        return v_mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_mobile
     *
     * @param v_mobile the value for tbl_sys_user.v_mobile
     * @mbg.generated
     */
    public void setV_mobile(String v_mobile) {
        this.v_mobile = v_mobile == null ? null : v_mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.i_status
     *
     * @return the value of tbl_sys_user.i_status
     * @mbg.generated
     */
    public Integer getI_status() {
        return i_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.i_status
     *
     * @param i_status the value for tbl_sys_user.i_status
     * @mbg.generated
     */
    public void setI_status(Integer i_status) {
        this.i_status = i_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_sex
     *
     * @return the value of tbl_sys_user.v_sex
     * @mbg.generated
     */
    public Long getV_sex() {
        return v_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_sex
     *
     * @param v_sex the value for tbl_sys_user.v_sex
     * @mbg.generated
     */
    public void setV_sex(Long v_sex) {
        this.v_sex = v_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_birth
     *
     * @return the value of tbl_sys_user.v_birth
     * @mbg.generated
     */
    public Date getV_birth() {
        return v_birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_birth
     *
     * @param v_birth the value for tbl_sys_user.v_birth
     * @mbg.generated
     */
    public void setV_birth(Date v_birth) {
        this.v_birth = v_birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_pic_id
     *
     * @return the value of tbl_sys_user.v_pic_id
     * @mbg.generated
     */
    public String getV_pic_id() {
        return v_pic_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_pic_id
     *
     * @param v_pic_id the value for tbl_sys_user.v_pic_id
     * @mbg.generated
     */
    public void setV_pic_id(String v_pic_id) {
        this.v_pic_id = v_pic_id == null ? null : v_pic_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_provincial_city
     *
     * @return the value of tbl_sys_user.v_provincial_city
     * @mbg.generated
     */
    public String getV_provincial_city() {
        return v_provincial_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_provincial_city
     *
     * @param v_provincial_city the value for tbl_sys_user.v_provincial_city
     * @mbg.generated
     */
    public void setV_provincial_city(String v_provincial_city) {
        this.v_provincial_city = v_provincial_city == null ? null : v_provincial_city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_address
     *
     * @return the value of tbl_sys_user.v_address
     * @mbg.generated
     */
    public String getV_address() {
        return v_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_address
     *
     * @param v_address the value for tbl_sys_user.v_address
     * @mbg.generated
     */
    public void setV_address(String v_address) {
        this.v_address = v_address == null ? null : v_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_hobby
     *
     * @return the value of tbl_sys_user.v_hobby
     * @mbg.generated
     */
    public String getV_hobby() {
        return v_hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_hobby
     *
     * @param v_hobby the value for tbl_sys_user.v_hobby
     * @mbg.generated
     */
    public void setV_hobby(String v_hobby) {
        this.v_hobby = v_hobby == null ? null : v_hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.i_work_order_flag
     *
     * @return the value of tbl_sys_user.i_work_order_flag
     * @mbg.generated
     */
    public Integer getI_work_order_flag() {
        return i_work_order_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.i_work_order_flag
     *
     * @param i_work_order_flag the value for tbl_sys_user.i_work_order_flag
     * @mbg.generated
     */
    public void setI_work_order_flag(Integer i_work_order_flag) {
        this.i_work_order_flag = i_work_order_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.i_send_phone_status
     *
     * @return the value of tbl_sys_user.i_send_phone_status
     * @mbg.generated
     */
    public Integer getI_send_phone_status() {
        return i_send_phone_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.i_send_phone_status
     *
     * @param i_send_phone_status the value for tbl_sys_user.i_send_phone_status
     * @mbg.generated
     */
    public void setI_send_phone_status(Integer i_send_phone_status) {
        this.i_send_phone_status = i_send_phone_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.i_send_message_status
     *
     * @return the value of tbl_sys_user.i_send_message_status
     * @mbg.generated
     */
    public Integer getI_send_message_status() {
        return i_send_message_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.i_send_message_status
     *
     * @param i_send_message_status the value for tbl_sys_user.i_send_message_status
     * @mbg.generated
     */
    public void setI_send_message_status(Integer i_send_message_status) {
        this.i_send_message_status = i_send_message_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.dt_createTime
     *
     * @return the value of tbl_sys_user.dt_createTime
     * @mbg.generated
     */
    public Date getDt_createTime() {
        return dt_createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.dt_createTime
     *
     * @param dt_createTime the value for tbl_sys_user.dt_createTime
     * @mbg.generated
     */
    public void setDt_createTime(Date dt_createTime) {
        this.dt_createTime = dt_createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.dt_modifyTime
     *
     * @return the value of tbl_sys_user.dt_modifyTime
     * @mbg.generated
     */
    public Date getDt_modifyTime() {
        return dt_modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.dt_modifyTime
     *
     * @param dt_modifyTime the value for tbl_sys_user.dt_modifyTime
     * @mbg.generated
     */
    public void setDt_modifyTime(Date dt_modifyTime) {
        this.dt_modifyTime = dt_modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_createid
     *
     * @return the value of tbl_sys_user.v_createid
     * @mbg.generated
     */
    public String getV_createid() {
        return v_createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_createid
     *
     * @param v_createid the value for tbl_sys_user.v_createid
     * @mbg.generated
     */
    public void setV_createid(String v_createid) {
        this.v_createid = v_createid == null ? null : v_createid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_user.v_modifyid
     *
     * @return the value of tbl_sys_user.v_modifyid
     * @mbg.generated
     */
    public String getV_modifyid() {
        return v_modifyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_user.v_modifyid
     *
     * @param v_modifyid the value for tbl_sys_user.v_modifyid
     * @mbg.generated
     */
    public void setV_modifyid(String v_modifyid) {
        this.v_modifyid = v_modifyid == null ? null : v_modifyid.trim();
    }
}