server:
  port: 8001
eureka:
  client:
    service-url:
      #      defaultZone: http://chongqing-eureka:8080/eureka/
      defaultZone: http://localhost:8008/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true


spring:
  application:
    #    name: chongqing-gateway
    name: shmashine-gateway
  redis:
    database: 3
    host: 10.0.0.113
    port: 6379
    password: shmashine@666
    timeout: 5000
  boot:
    admin:
      client:
        url: http://spring-boot-admin:8080 #配置admin-server地址
        username: shmashine
        password: shmashine
        instance:
          prefer-ip: true
          service-url: http://chongqing-gateway:8080
