eureka:
  client:
    service-url:
      defaultZone: http://shmashine-eureka:8080/eureka/

spring:
  redis:
    database: 1
    host: redis
    port: 6379
    password: shmashine@666
    timeout: 5000
  boot:
    admin:
      client:
        url: http://spring-boot-admin:9999/
        username: shmashine
        password: shmashine
        instance:
          prefer-ip: true
          service-url: http://shmashine-gateway:8001