server:
  # port: 8010
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://shmashine-eureka:8080/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

# sa-token 配置
sa-token:
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    database: 13  # 默认13
    host: 10.0.0.113
    port: 6379
    password: shmashine@666
    timeout: 5000

spring:
  application:
    name: shmashine-hk-camera-ym

  redis:
    database: 2
    host: redis
    port: 6379
    password: shmashine@666
    timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.dev.shmashine.com:3306/elevator_master?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: shmashine@666
    initialSize: 1
    minIdle: 3
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000

mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.shmashine.hikYunMou.entity
  configuration:
    map-underscore-to-camel-case: true    #开启驼峰功能
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
  global-config:
    db-config:
      update-strategy: NOT_EMPTY # 更新时，只更新非空字段
      insert-strategy: NOT_EMPTY # 新增时，只新增非空字段
      id-type: auto   #id自增长
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  row-bound-with-count: false
  # params: count=countSql

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

hik-cloud:
  application:
    client-id: 4ef54256cd5342e88f007bd691e9372d
    client-secret: 97345bcd72a8425697ffa894014c5ca4
    #client-id: 00f6f637092b480c81c5cb082390fb97
    #client-secret: 91218fae231449a983217ce35e818dff
    grant-type: client_credentials
  mq:
    topic:
      device-onoffline: open_device_onoffline
      cloud-video-record: open_cloud_video_result
    consumer:
      group-id: group1

ali-oss:
  use-internal: false # 服务器和OSS都位于青岛，可以使用内部地址上传到OSS

endpoint:
  sender-server: http://sender-service:8080