spring:
  redis:
    database: 1
    host: redis
    port: 6379
    password: shmashine@666
    timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    driverClassName: net.sf.log4jdbc.DriverSpy
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql8:3306/elevator_master?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: shmashine@666

camera:
  tysl:
    callback-base-url: http://tysl.camera.shmashine.com:8005

endpoint:
  image-identify: http://10.0.0.185:10089