eureka:
  client:
    service-url:
      defaultZone: http://shmashine-eureka:8080/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

sa-token:
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    database: 12  # 默认13
    host: redis
    port: 6379
    password: shmashine@666
    timeout: 5000

# kafka topic 名称
kafka:
  topic:
    consumer:
      fault: dev_oreo_fault
      event: dev_oreo_event
      tr: dev_oreo_tr
      preFault: dev_oreo_preFault
      hls: dev_hls_nezha
      faultConfirmBy6: dev_fault_confirm_by_6
      peopleFlowStatistics: dev_people_flow_statistics
    producer:
      hls: dev_failurevideo_nezha
      socket: dev_web_nezha
      ty: dev_fault_video_ty
      cubeFault: dev_cube_fault

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: MX
      username: shmashine
      password: Shmashine@666
  redis:
    database: 1
    host: redis
    port: 6379
    password: shmashine@666
    timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql8:3306/elevator_master?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: shmashine@666
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="secret20190219";
    consumer:
      bootstrap-servers: kafka:9092
      group-id: oreo-socket-group-testwu_test
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="secret20190219";

  boot:
    admin:
      client:
        url: http://spring-boot-admin:9999/
        username: shmashine
        password: shmashine
        instance:
          prefer-ip: true
          service-url: http://localhost:8004

endpoint:
  shmashine-camera-tysl: http://shmashine-camera-tysl:8080
  shmashine-hk-camera-ys: http://shmashine-hk-camera-ys:8080