eureka:
  client:
    service-url:
      defaultZone: http://shmashine-eureka:8080/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

# kafka topic 名称
kafka:
  topic:
    consumer:
      fault: dev_oreo_fault
      event: dev_oreo_event
      tr: dev_oreo_tr
      preFault: dev_oreo_preFault
      hls: dev_hls_nezha
      faultConfirmBy6: dev_fault_confirm_by_6
      peopleFlowStatistics: dev_people_flow_statistics
    producer:
      hls: dev_failurevideo_nezha
      socket: dev_web_nezha
      ty: dev_fault_video_ty
      cubeFault: dev_cube_fault

spring:
  data:
    mongodb:
      host: 10.0.0.124
      port: 27017
      database: MX
      username: shmashine
      password: Shmashine@666
  redis:
    database: 2
    host: 10.0.0.113
    port: 6379
    password: shmashine@666
    timeout: 5000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.0.113:3306/elevator_master?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: shmashine@666
  boot:
    admin:
      client:
        url: http://spring-boot-admin:8080 #配置admin-server地址
        username: shmashine
        password: shmashine
        instance:
          prefer-ip: true
          service-url: http://shmashine-fault:8080