# kafka topic 名称
kafka:
  topic:
    consumer:
      fault: pro_oreo_fault
      event: pro_oreo_event
      tr: pro_oreo_tr
      preFault: pro_oreo_preFault
      hls: pro_hls_nezha
      faultConfirmBy6: fault_confirm_by_6
      peopleFlowStatistics: pro_people_flow_statistics
    producer:
      hls: pro_failurevideo_nezha
      socket: pro_web_nezha
      ty: pro_fault_video_ty
      cubeFault: cube_fault

# sa-token 配置
sa-token:
  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    database: 13  # 默认13
    host: redis.tech.internal.shmashine.com
    port: 6379
    password: shmashine@666
    timeout: 5000

eureka:
  client:
    service-url:
      # defaultZone: http://172.31.183.101:8008/eureka/
      defaultZone: http://shmashine-eureka:8008/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

spring:
  data:
    mongodb:
      host: mongo.tech.internal.shmashine.com
      port: 27017
      database: MX
      username: shmashine
      password: Shmashine@666

  redis:
    database: 2
    host: redis.tech.internal.shmashine.com
    port: 6379
    password: shmashine@666
    timeout: 5000

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-m5e5x3037x8bn5br6.mysql.rds.aliyuncs.com:3306/elevator_master?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: elevator_master
    password: Shmash1ne@elevator_master

  kafka:
    producer:
      #bootstrap-servers: kafka:9092
      bootstrap-servers: kafka.pro.internal.shmashine.com:29092
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="secret20190219";
    consumer:
      #bootstrap-servers: kafka:9092
      bootstrap-servers: kafka.pro.internal.shmashine.com:29092
      group-id: shmashine-oreo-fault-pro
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 50
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="secret20190219";
  boot:
    admin:
      client:
        url: http://spring-boot-admin:9999/
        username: shmashine
        password: shmashine
        instance:
          prefer-ip: true
          # service-url: http://172.31.183.101:8004
          service-url: http://shmashine-fault:8004

endpoint:
  shmashine-camera-tysl: http://172.31.183.101:8014
  shmashine-hk-camera-ys: http://172.31.183.101:8009