server:
  port: 8003

# kafka topic 名称
kafka:
  topic:
    fault: pro_oreo_fault
    pre-fault: pro_oreo_preFault
    http: pro_netty_nezha
    socket: pro_web_nezha
    monitor: pro_oreo_monitor

eureka:
  client:
    service-url:
      # defaultZone: http://172.31.183.101:8008/eureka/
      defaultZone: http://127.0.0.1:8008/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true

spring:

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driverClassName: net.sf.log4jdbc.DriverSpy
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-m5e5x3037x8bn5br61o.mysql.rds.aliyuncs.com:3306/elevator_master?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: shmashine_dev
    password: Maixin@789#jhgfdsa

  kafka:
    producer:
      #bootstrap-servers: kafka:9092
      #bootstrap-servers: kafka.pro.shmashine.com:9092
      bootstrap-servers: 10.0.0.113:29092
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="secret20190219";
    consumer:
      #bootstrap-servers: kafka:9092
      #bootstrap-servers: kafka.pro.shmashine.com:9092
      bootstrap-servers: 10.0.0.113:29092
      group-id: pro-sender-local
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 1000
      #max-poll-records: 800
      heartbeat-interval: 3000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="secret20190219";
    listener:
      missing-topics-fatal: false

  boot:
    admin:
      client:
        url: http://spring-boot-admin:8080 #配置admin-server地址
        username: shmashine
        password: shmashine
        instance:
          prefer-ip: true
          # service-url: http://172.31.183.101:8003/api
          service-url: http://127.0.0.1:8003/api

springdoc:
  api-docs:
    enabled: true

#endpoint:
#  shmashine-applets: http://172.31.183.101:8012

endpoint:
  shmashine-socket: http://172.31.183.100:8002
  shmashine-hk-camera-ys: http://127.0.0.1:8009
  shmashine-hk-camera-ym: http://127.0.0.1:8010
  shmashine-camera-tysl: http://127.0.0.1:8014
  sender-server: http://127.0.0.1:8086