server:
  port: 8008
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #      defaultZone: http://chongqing-eureka:8080/eureka/
      defaultZone: http://localhost:8008/eureka/

spring:
  application:
    #    name: chongqing-eureka
    name: shmashine-eureka
  boot:
    admin:
      client:
        url: http://spring-boot-admin:8080 #配置admin-server地址
        username: shmashine
        password: shmashine
        instance:
          prefer-ip: true
          service-url: http://chongqing-eureka:8080

