spring:
  redis:
    database: 1
    host: redis
    port: 6379
    password: shmashine@666
    timeout: 5000
  boot:
    admin:
      client:
        url: http://spring-boot-admin:9999 #配置admin-server地址
        username: shmashine
        password: shmashine

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://shmashine-eureka:8008/eureka/

