# kafka topic 名称
kafka:
  topic:
    fault: pre_oreo_fault
    pre-fault: pre_oreo_preFault

spring:

  redis:
    database: 2
    host: 10.0.0.113
    port: 6379
    password: shmashine@666
    timeout: 5000

  kafka:
    producer:
      bootstrap-servers: kafka:9092
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="secret20190219";
    consumer:
      bootstrap-servers: kafka:9092
      group-id: oreo-socket-group-testwu-test
      #group-id: pro-sender
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 1000
      #max-poll-records: 800
      heartbeat-interval: 3000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="secret20190219";
    listener:
      missing-topics-fatal: false

  boot:
    admin:
      client:
        url: http://spring-boot-admin:8080/
        username: shmashine
        password: shmashine
        instance:
          prefer-ip: true
          service-url: http://HaierCamera-service:8080
