package com.shmashine.mapper;

import com.shmashine.entity.LoginInfo;
import com.shmashine.model.TblSysUser;

public interface TblSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String v_user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_user
     *
     * @mbg.generated
     */
    int insert(TblSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_user
     *
     * @mbg.generated
     */
    int insertSelective(TblSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_user
     *
     * @mbg.generated
     */
    TblSysUser selectByPrimaryKey(String v_user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TblSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TblSysUser record);

    int insertLoginInfo(LoginInfo loginInfo);
}